# Generated by Django 4.2.1 on 2023-05-20 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hockey', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='hockey',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='hockey',
            old_name='cat',
            new_name='position',
        ),
        migrations.RemoveField(
            model_name='hockey',
            name='content',
        ),
        migrations.RemoveField(
            model_name='hockey',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='hockey',
            name='time_create',
        ),
        migrations.RemoveField(
            model_name='hockey',
            name='time_update',
        ),
        migrations.AddField(
            model_name='hockey',
            name='namber',
            field=models.IntegerField(blank=None, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hockey',
            name='surname',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
