# Generated by Django 4.2.1 on 2023-05-21 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hockey', '0002_rename_name_category_type_rename_title_hockey_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grip', models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(blank=None)),
                ('sс', models.CharField(max_length=255)),
                ('gr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='hockey.grip')),
            ],
        ),
    ]
