# Generated by Django 4.2.1 on 2023-05-21 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hockey', '0003_grip_player'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='sс',
            new_name='sports_citizenship',
        ),
        migrations.AddField(
            model_name='hockey',
            name='s_c',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='hockey.player'),
        ),
    ]
