# Generated by Django 4.2.1 on 2023-05-21 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hockey', '0004_rename_sс_player_sports_citizenship_hockey_s_c'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hockey',
            old_name='s_c',
            new_name='sc',
        ),
    ]
