# Generated by Django 4.2.1 on 2023-05-21 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hockey', '0005_rename_s_c_hockey_sc'),
    ]

    operations = [
        migrations.CreateModel(
            name='SportsCitizenship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SC', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='player',
            name='sports_citizenship',
        ),
        migrations.AddField(
            model_name='player',
            name='sportscitizenship',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='hockey.sportscitizenship'),
        ),
    ]
