# Generated by Django 4.2.1 on 2023-05-21 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hockey', '0006_sportscitizenship_remove_player_sports_citizenship_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='sportscitizenship',
        ),
        migrations.AlterField(
            model_name='hockey',
            name='sc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='hockey.sportscitizenship'),
        ),
    ]
