# Generated by Django 4.2.1 on 2023-05-21 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hockey', '0007_remove_player_sportscitizenship_alter_hockey_sc'),
    ]

    operations = [
        migrations.AddField(
            model_name='hockey',
            name='player_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='hockey.player'),
        ),
    ]
