# Generated by Django 4.2.1 on 2023-05-21 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hockey', '0008_hockey_player_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hockey',
            name='sc',
        ),
        migrations.AddField(
            model_name='player',
            name='sc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='hockey.sportscitizenship'),
        ),
    ]
