# Generated by Django 4.2.1 on 2023-05-21 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hockey', '0009_remove_hockey_sc_player_sc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grip',
            name='grip',
            field=models.CharField(max_length=100),
        ),
    ]
