# Generated by Django 4.2.1 on 2023-05-21 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hockey', '0010_alter_grip_grip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grip',
            name='grip',
            field=models.CharField(max_length=255),
        ),
    ]
