# Generated by Django 4.2.1 on 2023-05-21 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hockey', '0011_alter_grip_grip'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Grip',
            new_name='Grips',
        ),
        migrations.RenameField(
            model_name='grips',
            old_name='grip',
            new_name='grips',
        ),
    ]
