# Generated by Django 4.2.1 on 2023-05-21 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hockey', '0012_rename_grip_grips_rename_grip_grips_grips'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='gr',
        ),
        migrations.DeleteModel(
            name='Grips',
        ),
    ]
