# Generated by Django 4.2.1 on 2023-05-21 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hockey', '0013_remove_player_gr_delete_grips'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grips', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='hockey',
            old_name='player_id',
            new_name='Idplayer',
        ),
        migrations.AddField(
            model_name='player',
            name='gr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='hockey.grips'),
        ),
    ]
