# Generated by Django 4.2.1 on 2023-05-21 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hockey', '0014_grips_rename_player_id_hockey_idplayer_player_gr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Trener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('Idplayer', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='hockey.player')),
                ('Idpost', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='hockey.post')),
            ],
        ),
    ]
