# Generated by Django 4.2.1 on 2023-05-21 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hockey', '0015_post_trener'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trener',
            name='Idplayer',
        ),
    ]
