# Generated by Django 4.2.1 on 2023-05-21 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hockey', '0018_prof_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='Idpost',
            new_name='Idprof',
        ),
    ]
