# Generated by Django 4.2.1 on 2023-05-21 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hockey', '0019_rename_idpost_staff_idprof'),
    ]

    operations = [
        migrations.AddField(
            model_name='hockey',
            name='img',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
